version: "3.9" # optional since v1.27.0
services:
  api:
    build: .
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      postgres:
        condition: service_healthy

    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=social_network_app
      - DB_USERNAME=myuser
      - DB_PASSWORD=password

  postgres:
    image: postgres:14.0
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "postgres",
          "-U",
          "postgres"
        ]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    logging:
      options:
        max-size: 10m
        max-file: "3"
    # ports:
    #   - '5432:5432'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - ./postgres-data_v14:/var/lib/postgresql/data
